be:
  sorondare:
    greeting:
      defaultFormat: Hello %s
      defaultName: Me

quarkus:
  liquibase:
    change-log: db/changeLog.yml
    migrate-at-start: true

  security:
    users:
      file:
        enabled: true
        users: users.properties
        roles: roles.properties
        realm-name: QuarkusTest
        plain-text: false

  log:
    level: INFO
