name: Docker package

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    uses: Sorondare/quarkus-test/.github/workflows/build.yml@latest
    with:
      produce-jar-artifact: true

  package:
    runs-on: ubuntu-latest
    name: Docker package
    steps:
      - name: Checkout Dockerfile
        uses: actions/checkout@v2
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: quarkus-jar
      - name: Display structure of downloaded files
        run: ls -R